import type { ComponentProps } from 'react';
/* GENERATED by scripts/gen-elements.mjs from the components' TypeScript props. Do not edit. */
import * as C from '../index';
import type { ElementSpec } from './define';

export const elementSpecs: ElementSpec[] = [
  { tag: 'co-ai-suggestion', component: C.AISuggestion as never, props: { title: 'string', source: 'string', confidence: 'string', children: 'node', actions: 'node', defaultChecked: 'boolean', defaultValue: 'json', autoFocus: 'boolean' } },
  { tag: 'co-alert', component: C.Alert as never, props: { tone: 'string', title: 'node', children: 'node', actions: 'node', onDismiss: 'event', defaultChecked: 'boolean', defaultValue: 'json', autoFocus: 'boolean' } },
  { tag: 'co-appointment-chip', component: C.AppointmentChip as never, props: { time: 'string', patient: 'string', type: 'string', status: 'json', colorBy: 'string', color: 'string', telehealth: 'boolean', paid: 'boolean', size: 'string', defaultChecked: 'boolean', defaultValue: 'json', autoFocus: 'boolean', disabled: 'boolean', name: 'string', value: 'json' } },
  { tag: 'co-avatar', component: C.Avatar as never, props: { name: 'string', src: 'string', size: 'string', color: 'string', status: 'string', defaultChecked: 'boolean', defaultValue: 'json', autoFocus: 'boolean' } },
  { tag: 'co-badge', component: C.Badge as never, props: { tone: 'string', shape: 'string', size: 'string', icon: 'string', dot: 'boolean', children: 'node', defaultChecked: 'boolean', defaultValue: 'json', autoFocus: 'boolean' } },
  { tag: 'co-button', component: C.Button as never, props: { variant: 'string', size: 'string', loading: 'boolean', iconLeft: 'string', iconRight: 'string', full: 'boolean', pressed: 'boolean', href: 'string', target: 'json', rel: 'string', children: 'node', defaultChecked: 'boolean', defaultValue: 'json', autoFocus: 'boolean', type: 'string', disabled: 'boolean', name: 'string', value: 'json' } },
  { tag: 'co-card', component: C.Card as never, props: { title: 'node', subtitle: 'node', actions: 'node', footer: 'node', flat: 'boolean', padding: 'string', as: 'json', children: 'node', defaultChecked: 'boolean', defaultValue: 'json', autoFocus: 'boolean' } },
  { tag: 'co-checkbox', component: C.Checkbox as never, props: { label: 'node', checked: 'boolean', defaultChecked: 'boolean', indeterminate: 'boolean', description: 'node', error: 'boolean', disabled: 'boolean', defaultValue: 'json', autoFocus: 'boolean', name: 'string', value: 'json', accept: 'string', autoComplete: 'json', max: 'json', maxLength: 'number', min: 'json', multiple: 'boolean', placeholder: 'string', readOnly: 'boolean', required: 'boolean', step: 'json' } },
  { tag: 'co-command-palette', component: C.CommandPalette as never, props: { items: 'json', open: 'boolean', query: 'string', defaultQuery: 'string', onQueryChange: 'event', placeholder: 'string', onSelect: 'event', onClose: 'event', maxResults: 'number', inline: 'boolean', defaultChecked: 'boolean', defaultValue: 'json', autoFocus: 'boolean', ref: 'json' } },
  { tag: 'co-drawer', component: C.Drawer as never, props: { open: 'boolean', title: 'string', side: 'string', developer: 'boolean', sections: 'json', children: 'node', footer: 'node', width: 'number', onClose: 'event', inline: 'boolean', defaultChecked: 'boolean', defaultValue: 'json', autoFocus: 'boolean' } },
  { tag: 'co-icon', component: C.Icon as never, props: { name: 'string', size: 'number', strokeWidth: 'number', label: 'string', type: 'string', max: 'json', min: 'json' } },
  { tag: 'co-icon-button', component: C.IconButton as never, props: { icon: 'string', label: 'string', variant: 'string', size: 'string', badge: 'json', disabled: 'boolean', defaultChecked: 'boolean', defaultValue: 'json', autoFocus: 'boolean', type: 'string', name: 'string', value: 'json' } },
  { tag: 'co-kebab-menu', component: C.KebabMenu as never, props: { items: 'json', label: 'string', horizontal: 'boolean', align: 'string', defaultOpen: 'boolean', open: 'boolean', onOpenChange: 'event', className: 'string' } },
  { tag: 'co-menu', component: C.Menu as never, props: { items: 'json', align: 'string', inline: 'boolean', label: 'string', onClose: 'event', autoFocus: 'json', style: 'json', defaultChecked: 'boolean', defaultValue: 'json' } },
  { tag: 'co-modal', component: C.Modal as never, props: { open: 'boolean', title: 'node', kind: 'string', size: 'string', children: 'node', primaryLabel: 'string', cancelLabel: 'string', onPrimary: 'event', onClose: 'event', loading: 'boolean', primaryDisabled: 'boolean', footer: 'node', closeOnScrim: 'boolean', inline: 'boolean', defaultChecked: 'boolean', defaultValue: 'json', autoFocus: 'boolean' } },
  { tag: 'co-overlay', component: C.Overlay as never, props: { inline: 'boolean', side: 'string', onScrimPress: 'event', children: 'node', defaultChecked: 'boolean', defaultValue: 'json', autoFocus: 'boolean' } },
  { tag: 'co-popover', component: C.Popover as never, props: { trigger: 'node', title: 'string', children: 'node', align: 'string', defaultOpen: 'boolean', open: 'boolean', onOpenChange: 'event', triggerVariant: 'string', size: 'string', label: 'string', className: 'string' } },
  { tag: 'co-radio', component: C.Radio as never, props: { label: 'node', description: 'node', disabled: 'boolean', defaultChecked: 'boolean', defaultValue: 'json', autoFocus: 'boolean', name: 'string', value: 'json', accept: 'string', autoComplete: 'json', checked: 'boolean', max: 'json', maxLength: 'number', min: 'json', multiple: 'boolean', placeholder: 'string', readOnly: 'boolean', required: 'boolean', step: 'json' } },
  { tag: 'co-radio-group', component: C.RadioGroup as never, props: { label: 'node', options: 'json', value: 'string', defaultValue: 'string', inline: 'boolean', required: 'boolean', error: 'node', disabled: 'boolean', name: 'string', onChange: 'event', defaultChecked: 'boolean', autoFocus: 'boolean' } },
  { tag: 'co-spinner', component: C.Spinner as never, props: { size: 'string', tone: 'string', label: 'string', defaultChecked: 'boolean', defaultValue: 'json', autoFocus: 'boolean' } },
  { tag: 'co-status-tag', component: C.StatusTag as never, props: { kind: 'string', status: 'string', tone: 'string', icon: 'boolean', defaultChecked: 'boolean', defaultValue: 'json', autoFocus: 'boolean', size: 'string', shape: 'string', dot: 'boolean' } },
  { tag: 'co-success-dialog', component: C.SuccessDialog as never, props: { title: 'string', children: 'node', okayLabel: 'string', onOkay: 'event', secondary: 'string', onSecondary: 'event', open: 'boolean', onClose: 'event', inline: 'boolean', defaultChecked: 'boolean', defaultValue: 'json', autoFocus: 'boolean' } },
  { tag: 'co-toast', component: C.Toast as never, props: { message: 'string', tone: 'string', action: 'string', onAction: 'event', onDismiss: 'event', inline: 'boolean', children: 'node', defaultChecked: 'boolean', defaultValue: 'json', autoFocus: 'boolean' } },
  { tag: 'co-toast-provider', component: C.ToastProvider as never, props: { children: 'node', max: 'number', duration: 'number', className: 'string' } },
];

/** `<co-ai-suggestion>`: the AISuggestion component as a custom element. */
export type CoAiSuggestionElement = HTMLElement & Partial<Pick<ComponentProps<typeof C.AISuggestion>, "title" | "source" | "confidence" | "defaultChecked" | "defaultValue" | "autoFocus">>;
/** `<co-alert>`: the Alert component as a custom element. */
export type CoAlertElement = HTMLElement & Partial<Pick<ComponentProps<typeof C.Alert>, "tone" | "defaultChecked" | "defaultValue" | "autoFocus">>;
/** `<co-appointment-chip>`: the AppointmentChip component as a custom element. */
export type CoAppointmentChipElement = HTMLElement & Partial<Pick<ComponentProps<typeof C.AppointmentChip>, "time" | "patient" | "type" | "status" | "colorBy" | "color" | "telehealth" | "paid" | "size" | "defaultChecked" | "defaultValue" | "autoFocus" | "disabled" | "name" | "value">>;
/** `<co-avatar>`: the Avatar component as a custom element. */
export type CoAvatarElement = HTMLElement & Partial<Pick<ComponentProps<typeof C.Avatar>, "name" | "src" | "size" | "color" | "status" | "defaultChecked" | "defaultValue" | "autoFocus">>;
/** `<co-badge>`: the Badge component as a custom element. */
export type CoBadgeElement = HTMLElement & Partial<Pick<ComponentProps<typeof C.Badge>, "tone" | "shape" | "size" | "icon" | "dot" | "defaultChecked" | "defaultValue" | "autoFocus">>;
/** `<co-button>`: the Button component as a custom element. */
export type CoButtonElement = HTMLElement & Partial<Pick<ComponentProps<typeof C.Button>, "variant" | "size" | "loading" | "iconLeft" | "iconRight" | "full" | "pressed" | "href" | "target" | "rel" | "defaultChecked" | "defaultValue" | "autoFocus" | "type" | "disabled" | "name" | "value">>;
/** `<co-card>`: the Card component as a custom element. */
export type CoCardElement = HTMLElement & Partial<Pick<ComponentProps<typeof C.Card>, "flat" | "padding" | "as" | "defaultChecked" | "defaultValue" | "autoFocus">>;
/** `<co-checkbox>`: the Checkbox component as a custom element. */
export type CoCheckboxElement = HTMLElement & Partial<Pick<ComponentProps<typeof C.Checkbox>, "checked" | "defaultChecked" | "indeterminate" | "error" | "disabled" | "defaultValue" | "autoFocus" | "name" | "value" | "accept" | "autoComplete" | "max" | "maxLength" | "min" | "multiple" | "placeholder" | "readOnly" | "required" | "step">>;
/** `<co-command-palette>`: the CommandPalette component as a custom element. */
export type CoCommandPaletteElement = HTMLElement & Partial<Pick<ComponentProps<typeof C.CommandPalette>, "items" | "open" | "query" | "defaultQuery" | "placeholder" | "maxResults" | "inline" | "defaultChecked" | "defaultValue" | "autoFocus" | "ref">>;
/** `<co-drawer>`: the Drawer component as a custom element. */
export type CoDrawerElement = HTMLElement & Partial<Pick<ComponentProps<typeof C.Drawer>, "open" | "title" | "side" | "developer" | "sections" | "width" | "inline" | "defaultChecked" | "defaultValue" | "autoFocus">>;
/** `<co-icon>`: the Icon component as a custom element. */
export type CoIconElement = HTMLElement & Partial<Pick<ComponentProps<typeof C.Icon>, "name" | "size" | "strokeWidth" | "label" | "type" | "max" | "min">>;
/** `<co-icon-button>`: the IconButton component as a custom element. */
export type CoIconButtonElement = HTMLElement & Partial<Pick<ComponentProps<typeof C.IconButton>, "icon" | "label" | "variant" | "size" | "badge" | "disabled" | "defaultChecked" | "defaultValue" | "autoFocus" | "type" | "name" | "value">>;
/** `<co-kebab-menu>`: the KebabMenu component as a custom element. */
export type CoKebabMenuElement = HTMLElement & Partial<Pick<ComponentProps<typeof C.KebabMenu>, "items" | "label" | "horizontal" | "align" | "defaultOpen" | "open" | "className">>;
/** `<co-menu>`: the Menu component as a custom element. */
export type CoMenuElement = HTMLElement & Partial<Pick<ComponentProps<typeof C.Menu>, "items" | "align" | "inline" | "label" | "autoFocus" | "style" | "defaultChecked" | "defaultValue">>;
/** `<co-modal>`: the Modal component as a custom element. */
export type CoModalElement = HTMLElement & Partial<Pick<ComponentProps<typeof C.Modal>, "open" | "kind" | "size" | "primaryLabel" | "cancelLabel" | "loading" | "primaryDisabled" | "closeOnScrim" | "inline" | "defaultChecked" | "defaultValue" | "autoFocus">>;
/** `<co-overlay>`: the Overlay component as a custom element. */
export type CoOverlayElement = HTMLElement & Partial<Pick<ComponentProps<typeof C.Overlay>, "inline" | "side" | "defaultChecked" | "defaultValue" | "autoFocus">>;
/** `<co-popover>`: the Popover component as a custom element. */
export type CoPopoverElement = HTMLElement & Partial<Pick<ComponentProps<typeof C.Popover>, "title" | "align" | "defaultOpen" | "open" | "triggerVariant" | "size" | "label" | "className">>;
/** `<co-radio>`: the Radio component as a custom element. */
export type CoRadioElement = HTMLElement & Partial<Pick<ComponentProps<typeof C.Radio>, "disabled" | "defaultChecked" | "defaultValue" | "autoFocus" | "name" | "value" | "accept" | "autoComplete" | "checked" | "max" | "maxLength" | "min" | "multiple" | "placeholder" | "readOnly" | "required" | "step">>;
/** `<co-radio-group>`: the RadioGroup component as a custom element. */
export type CoRadioGroupElement = HTMLElement & Partial<Pick<ComponentProps<typeof C.RadioGroup>, "options" | "value" | "defaultValue" | "inline" | "required" | "disabled" | "name" | "defaultChecked" | "autoFocus">>;
/** `<co-spinner>`: the Spinner component as a custom element. */
export type CoSpinnerElement = HTMLElement & Partial<Pick<ComponentProps<typeof C.Spinner>, "size" | "tone" | "label" | "defaultChecked" | "defaultValue" | "autoFocus">>;
/** `<co-status-tag>`: the StatusTag component as a custom element. */
export type CoStatusTagElement = HTMLElement & Partial<Pick<ComponentProps<typeof C.StatusTag>, "kind" | "status" | "tone" | "icon" | "defaultChecked" | "defaultValue" | "autoFocus" | "size" | "shape" | "dot">>;
/** `<co-success-dialog>`: the SuccessDialog component as a custom element. */
export type CoSuccessDialogElement = HTMLElement & Partial<Pick<ComponentProps<typeof C.SuccessDialog>, "title" | "okayLabel" | "secondary" | "open" | "inline" | "defaultChecked" | "defaultValue" | "autoFocus">>;
/** `<co-toast>`: the Toast component as a custom element. */
export type CoToastElement = HTMLElement & Partial<Pick<ComponentProps<typeof C.Toast>, "message" | "tone" | "action" | "inline" | "defaultChecked" | "defaultValue" | "autoFocus">>;
/** `<co-toast-provider>`: the ToastProvider component as a custom element. */
export type CoToastProviderElement = HTMLElement & Partial<Pick<ComponentProps<typeof C.ToastProvider>, "max" | "duration" | "className">>;

declare global {
  interface HTMLElementTagNameMap {
    'co-ai-suggestion': CoAiSuggestionElement;
    'co-alert': CoAlertElement;
    'co-appointment-chip': CoAppointmentChipElement;
    'co-avatar': CoAvatarElement;
    'co-badge': CoBadgeElement;
    'co-button': CoButtonElement;
    'co-card': CoCardElement;
    'co-checkbox': CoCheckboxElement;
    'co-command-palette': CoCommandPaletteElement;
    'co-drawer': CoDrawerElement;
    'co-icon': CoIconElement;
    'co-icon-button': CoIconButtonElement;
    'co-kebab-menu': CoKebabMenuElement;
    'co-menu': CoMenuElement;
    'co-modal': CoModalElement;
    'co-overlay': CoOverlayElement;
    'co-popover': CoPopoverElement;
    'co-radio': CoRadioElement;
    'co-radio-group': CoRadioGroupElement;
    'co-spinner': CoSpinnerElement;
    'co-status-tag': CoStatusTagElement;
    'co-success-dialog': CoSuccessDialogElement;
    'co-toast': CoToastElement;
    'co-toast-provider': CoToastProviderElement;
  }
}
