#!/usr/bin/env node
/**
 * Generates the token outputs from src/tokens/tokens.json (the single source of truth):
 *   src/styles/tokens.css   CSS custom properties, one block per theme
 *   src/tokens/tokens.ts    typed JS/TS export of every token and theme
 *
 * Every variable is namespaced `--co-<token>` so the library never collides with a host app's
 * own `--primary` or `--border`. Themes are selected with `data-co-theme="<id>"` on any element;
 * the first theme (Classic) also applies at :root so components work with no setup.
 * Each theme block carries its full themed set, so themes nest in any order.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const src = JSON.parse(readFileSync(resolve(root, 'src/tokens/tokens.json'), 'utf8'));

const PREFIX = 'co';
const themes = src.color.themes;
const themeIds = themes.map((t) => t.id);
const defaultTheme = themeIds[0];
const SCALAR_FAMILIES = ['spacing', 'radius', 'shadow', 'zIndex', 'density'];

const cssVar = (name) => `--${PREFIX}-${name}`;
const valueFor = (value, theme) =>
  value && typeof value === 'object' ? (value[theme] ?? value[defaultTheme]) : value;

/** Resolve `{other-token}` aliases into var() references. */
const resolveValue = (v) =>
  typeof v === 'string' ? v.replace(/\{([A-Za-z0-9_.-]+)\}/g, (_, n) => `var(${cssVar(n)})`) : String(v);

const themed = [...src.color.tokens];
for (const fam of SCALAR_FAMILIES) for (const t of src[fam]?.tokens ?? []) themed.push(t);

function block(selector, theme, includeStatic) {
  const lines = [];
  for (const t of themed) {
    const isThemed = t.value && typeof t.value === 'object';
    if (!includeStatic && !isThemed) continue;
    const v = valueFor(t.value, theme);
    lines.push(`  ${cssVar(t.name)}: ${resolveValue(v)};`);
  }
  if (includeStatic) {
    for (const [k, v] of Object.entries(src.type.families)) lines.push(`  ${cssVar('font-' + k)}: ${v};`);
    for (const g of src.type.groups)
      for (const s of g.styles) {
        lines.push(`  ${cssVar('text-' + s.name + '-size')}: ${s.fontSize};`);
        lines.push(`  ${cssVar('text-' + s.name + '-line')}: ${s.lineHeight};`);
        lines.push(`  ${cssVar('text-' + s.name + '-weight')}: ${s.fontWeight};`);
      }
  }
  if (theme === 'dark') lines.push('  color-scheme: dark;');
  else if (includeStatic) lines.push('  color-scheme: light;');
  return `${selector} {\n${lines.join('\n')}\n}`;
}

const header = `/* CareOS design tokens. GENERATED by scripts/build-tokens.mjs from src/tokens/tokens.json. Do not edit. */\n`;
const parts = [header, block(`:root,\n[data-co-theme="${defaultTheme}"]`, defaultTheme, true)];
for (const id of themeIds.slice(1)) parts.push(block(`[data-co-theme="${id}"]`, id, false));
writeFileSync(resolve(root, 'src/styles/tokens.css'), parts.join('\n\n') + '\n');

/* ---------- typed TS export ---------- */
const tokenEntries = (list) =>
  list.map((t) => ({ name: t.name, cssVar: cssVar(t.name), value: t.value, usage: t.usage ?? '' }));
const out = {
  name: src.name,
  themes,
  defaultTheme,
  color: tokenEntries(src.color.tokens),
  ...Object.fromEntries(SCALAR_FAMILIES.map((f) => [f, tokenEntries(src[f]?.tokens ?? [])])),
  typography: {
    families: Object.fromEntries(
      Object.entries(src.type.families).map(([k, v]) => [k, { cssVar: cssVar('font-' + k), value: v }])
    ),
    groups: src.type.groups,
  },
};
const ts = `/* GENERATED by scripts/build-tokens.mjs from src/tokens/tokens.json. Do not edit. */

export type ThemeId = ${themeIds.map((t) => `'${t}'`).join(' | ')};

export interface TokenEntry<V = string | Record<string, string>> {
  /** Token name as used in tokens.json, for example \`primary\`. */
  name: string;
  /** CSS custom property, for example \`--co-primary\`. */
  cssVar: string;
  /** Value, or a value per theme. */
  value: V;
  /** Where the token goes and what reads on it. */
  usage: string;
}

export const themeIds = ${JSON.stringify(themeIds)} as const satisfies readonly ThemeId[];

export const tokens = ${JSON.stringify(out, null, 2)} as const;

export type ColorToken = (typeof tokens.color)[number]['name'];

/** \`var(--co-<name>)\` for any token name. */
export function tokenVar(name: string): string {
  return \`var(--co-\${name})\`;
}

/** The value of a colour token in a theme (falls back to the default theme). */
export function colorValue(name: ColorToken, theme: ThemeId = '${defaultTheme}'): string | undefined {
  const t = tokens.color.find((c) => c.name === name);
  if (!t) return undefined;
  const v = t.value as string | Record<string, string>;
  return typeof v === 'string' ? v : (v[theme] ?? v['${defaultTheme}']);
}
`;
writeFileSync(resolve(root, 'src/tokens/tokens.ts'), ts);
console.log(`tokens: ${themed.length} tokens x ${themeIds.length} themes -> src/styles/tokens.css, src/tokens/tokens.ts`);
