#!/usr/bin/env node
/** Regenerates src/index.ts from the component folders (each exports from its own index.ts). */
import { existsSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const dir = resolve(root, 'src/components');
const names = readdirSync(dir, { withFileTypes: true })
  .filter((d) => d.isDirectory() && existsSync(resolve(dir, d.name, 'index.ts')))
  .map((d) => d.name)
  .sort();
const out = `/* GENERATED by scripts/gen-index.mjs. Do not edit: add a component folder with an index.ts instead. */
export * from './tokens/tokens';
export * from './clinical';
export { cx } from './internal/cx';
${names.map((n) => `export * from './components/${n}';`).join('\n')}
`;
writeFileSync(resolve(root, 'src/index.ts'), out);

// Per-component CSS additions live in src/styles/extra/<Name>.css; collect them in one import file.
const extras = readdirSync(resolve(root, 'src/styles/extra'))
  .filter((f) => f.endsWith('.css'))
  .sort();
writeFileSync(
  resolve(root, 'src/styles/extra.css'),
  `/* GENERATED by scripts/gen-index.mjs from src/styles/extra/*.css. Do not edit. */\n${extras.map((f) => `@import './extra/${f}';`).join('\n')}\n`
);
console.log(`index: ${names.length} component folders`);
