/* GENERATED by scripts/build-tokens.mjs from src/tokens/tokens.json. Do not edit. */

export type ThemeId = 'classic' | 'sidebar' | 'rail' | 'command' | 'dark';

export interface TokenEntry<V = string | Record<string, string>> {
  /** Token name as used in tokens.json, for example `primary`. */
  name: string;
  /** CSS custom property, for example `--co-primary`. */
  cssVar: string;
  /** Value, or a value per theme. */
  value: V;
  /** Where the token goes and what reads on it. */
  usage: string;
}

export const themeIds = ["classic","sidebar","rail","command","dark"] as const satisfies readonly ThemeId[];

export const tokens = {
  "name": "CareOS",
  "themes": [
    {
      "id": "classic",
      "name": "Classic"
    },
    {
      "id": "sidebar",
      "name": "Clinical Sidebar"
    },
    {
      "id": "rail",
      "name": "Focus Rail"
    },
    {
      "id": "command",
      "name": "Command Bar"
    },
    {
      "id": "dark",
      "name": "Dark"
    }
  ],
  "defaultTheme": "classic",
  "color": [
    {
      "name": "primary",
      "cssVar": "--co-primary",
      "value": {
        "classic": "#2E5880",
        "sidebar": "#0F766E",
        "rail": "#3B4FD8",
        "command": "#166534",
        "dark": "#2DD4BF"
      },
      "usage": "Primary buttons, active tab underline, selected slot and chip fills, focus of the brand. Text `primary-ink` on it. As text (`link`) on `surface`."
    },
    {
      "name": "primary-hover",
      "cssVar": "--co-primary-hover",
      "value": {
        "classic": "#244A6D",
        "sidebar": "#0C615A",
        "rail": "#3041B1",
        "command": "#12532B",
        "dark": "#5EEAD4"
      },
      "usage": "Hover fill of primary buttons (source: primary mixed 82% with black)."
    },
    {
      "name": "primary-strong",
      "cssVar": "--co-primary-strong",
      "value": {
        "classic": "#1D4F7C",
        "sidebar": "#0C5C56",
        "rail": "#2E3EA8",
        "command": "#114F29",
        "dark": "#5EEAD4"
      },
      "usage": "Text on `primary-soft` (active nav item, info tag, selected segmented button); pressed fills; mobile and kiosk header bar with white text."
    },
    {
      "name": "primary-soft",
      "cssVar": "--co-primary-soft",
      "value": {
        "classic": "#DEE9FB",
        "sidebar": "#DDECEB",
        "rail": "#E4E6FA",
        "command": "#DEE9E3",
        "dark": "#123B37"
      },
      "usage": "Active nav item, info tag and selected secondary button background. Holds `primary-strong` text."
    },
    {
      "name": "primary-tint",
      "cssVar": "--co-primary-tint",
      "value": {
        "classic": "#F5F8FD",
        "sidebar": "#F3F8F8",
        "rail": "#F5F6FD",
        "command": "#F3F7F5",
        "dark": "#13201F"
      },
      "usage": "Hover wash on free calendar cells and selected pick cards."
    },
    {
      "name": "primary-line",
      "cssVar": "--co-primary-line",
      "value": {
        "classic": "#5281DD",
        "sidebar": "#6FADA8",
        "rail": "#8995E8",
        "command": "#73A385",
        "dark": "#2A9D8F"
      },
      "usage": "Border of a pressed secondary button; the Blue appointment colour."
    },
    {
      "name": "line-soft",
      "cssVar": "--co-line-soft",
      "value": {
        "classic": "#C9D6E6",
        "sidebar": "#CAE1DF",
        "rail": "#D4D8F6",
        "command": "#CCDDD2",
        "dark": "#24423F"
      },
      "usage": "Border of the read-only lock banner and dashed drop zones."
    },
    {
      "name": "link",
      "cssVar": "--co-link",
      "value": {
        "classic": "#2F6FA8",
        "sidebar": "#0F766E",
        "rail": "#3B4FD8",
        "command": "#166534",
        "dark": "#5EEAD4"
      },
      "usage": "Inline links and link buttons on `surface` and `canvas`."
    },
    {
      "name": "primary-ink",
      "cssVar": "--co-primary-ink",
      "value": {
        "classic": "#FFFFFF",
        "sidebar": "#FFFFFF",
        "rail": "#FFFFFF",
        "command": "#FFFFFF",
        "dark": "#042F2B"
      },
      "usage": "Text and icons on `primary` fills."
    },
    {
      "name": "ink",
      "cssVar": "--co-ink",
      "value": {
        "classic": "#1F2937",
        "sidebar": "#0B1F1E",
        "rail": "#111827",
        "command": "#111827",
        "dark": "#E8EFEE"
      },
      "usage": "Body text and headings on `surface`, `canvas`, `surface-muted`."
    },
    {
      "name": "ink-2",
      "cssVar": "--co-ink-2",
      "value": {
        "classic": "#374151",
        "sidebar": "#2E3F3D",
        "rail": "#334155",
        "command": "#374151",
        "dark": "#C5D1CF"
      },
      "usage": "Secondary text: table cells, notes, unselected nav items, on `surface` and `surface-muted`."
    },
    {
      "name": "muted",
      "cssVar": "--co-muted",
      "value": {
        "classic": "#586779",
        "sidebar": "#526A63",
        "rail": "#596879",
        "command": "#586779",
        "dark": "#ADBDB8"
      },
      "usage": "Helper text, column meta, inactive tabs, placeholder, on `surface` and `canvas`. Contrast fix applied 10/09/2026 (lightness only, hue and saturation kept, WCAG 2 formula): Classic was #6B7280 (canvas 4.32:1, surface-muted 4.39:1, under 4.5:1 for help and caption text); Focus Rail was #64748B (canvas 4.41:1, surface-muted 4.17:1, under 4.5:1 for help and caption text); Command Bar was #6B7280 (surface-muted 4.39:1, under 4.5:1 for help and caption text)."
    },
    {
      "name": "border",
      "cssVar": "--co-border",
      "value": {
        "classic": "#CBD5E1",
        "sidebar": "#CBD5D3",
        "rail": "#CDD5E0",
        "command": "#CBD5D8",
        "dark": "#405351"
      },
      "usage": "Card, input, table and divider lines. Decorative only; inputs rely on the label plus this line. Contrast fix applied 10/09/2026 (lightness only, hue and saturation kept, WCAG 2 formula): Classic was #E3E6EA (surface 1.25:1, under 3:1 for input boundary (WCAG 1.4.11 non-text, 3:1)); Clinical Sidebar was #E4E0D8 (surface 1.32:1, under 3:1 for input boundary (WCAG 1.4.11 non-text, 3:1)); Focus Rail was #E2E5EE (surface 1.26:1, under 3:1 for input boundary (WCAG 1.4.11 non-text, 3:1)); Command Bar was #E5E7EB (surface 1.24:1, under 3:1 for input boundary (WCAG 1.4.11 non-text, 3:1)). Contrast fix applied 10/09/2026 (lightness only, hue and saturation kept, WCAG 2 formula): Dark was #2E3D3B (surface 1.45:1, under 3:1 for input boundary (WCAG 1.4.11 non-text, 3:1))."
    },
    {
      "name": "border-strong",
      "cssVar": "--co-border-strong",
      "value": {
        "classic": "#8291A5",
        "sidebar": "#8291A5",
        "rail": "#8291A5",
        "command": "#8291A5",
        "dark": "#718884"
      },
      "usage": "Unchecked switch track, dashed add button, signature pad border."
    },
    {
      "name": "surface",
      "cssVar": "--co-surface",
      "value": {
        "classic": "#FFFFFF",
        "sidebar": "#FFFFFF",
        "rail": "#FFFFFF",
        "command": "#FFFFFF",
        "dark": "#172120"
      },
      "usage": "Cards, modals, drawers, menus, inputs, table body."
    },
    {
      "name": "surface-muted",
      "cssVar": "--co-surface-muted",
      "value": {
        "classic": "#F3F4F6",
        "sidebar": "#EFECE5",
        "rail": "#EEF0F5",
        "command": "#F3F4F6",
        "dark": "#22302E"
      },
      "usage": "Table header, read-only input, hover row, note box, neutral tag."
    },
    {
      "name": "surface-alt",
      "cssVar": "--co-surface-alt",
      "value": {
        "classic": "#EEF2F7",
        "sidebar": "#EEF3F1",
        "rail": "#ECEFF7",
        "command": "#F3F6F4",
        "dark": "#1C2B29"
      },
      "usage": "Lock banner, Scheduled appointment chip, Viewing as pill."
    },
    {
      "name": "canvas",
      "cssVar": "--co-canvas",
      "value": {
        "classic": "#F4F7FA",
        "sidebar": "#F3F7F6",
        "rail": "#F4F7FB",
        "command": "#F4F7F8",
        "dark": "#111C1B"
      },
      "usage": "Page background behind cards."
    },
    {
      "name": "canvas-soft",
      "cssVar": "--co-canvas-soft",
      "value": {
        "classic": "#FAFBFC",
        "sidebar": "#FAF9F6",
        "rail": "#F9FAFC",
        "command": "#F9FAFB",
        "dark": "#121A19"
      },
      "usage": "Search box fill, calendar time column, drop zone fill."
    },
    {
      "name": "accent",
      "cssVar": "--co-accent",
      "value": {
        "classic": "#926723",
        "sidebar": "#AE5009",
        "rail": "#CA381A",
        "command": "#956603",
        "dark": "#F59E0B"
      },
      "usage": "Style highlight (Classic: the gold account avatar #d7a657): active patient tab top line (Focus Rail coral), New badge text, account avatar fill. Contrast fix applied 10/09/2026 (lightness only, hue and saturation kept, WCAG 2 formula): Classic was #D7A657 (surface-muted 2.01:1, surface 2.21:1, on-accent 2.21:1, under 4.5:1 for accent as text, and white initials on the accent avatar); Clinical Sidebar was #B45309 (surface-muted 4.26:1, under 4.5:1 for accent as text); Focus Rail was #E8654A (surface-muted 2.88:1, surface 3.29:1, on-accent 3.29:1, under 4.5:1 for accent as text, and white initials on the accent avatar); Command Bar was #CA8A04 (surface-muted 2.67:1, surface 2.94:1, on-accent 2.94:1, under 4.5:1 for accent as text, and white initials on the accent avatar)."
    },
    {
      "name": "nav-bg",
      "cssVar": "--co-nav-bg",
      "value": {
        "classic": "#285278",
        "sidebar": "#FFFFFF",
        "rail": "#1E2A44",
        "command": "#FFFFFF",
        "dark": "#172120"
      },
      "usage": "Navigation surface: navy top bar in Classic, white for Sidebar and Command Bar, slate rail for Focus Rail."
    },
    {
      "name": "nav-ink",
      "cssVar": "--co-nav-ink",
      "value": {
        "classic": "#FFFFFF",
        "sidebar": "#0B1F1E",
        "rail": "#FFFFFF",
        "command": "#111827",
        "dark": "#E8EFEE"
      },
      "usage": "Active text and icons on `nav-bg`."
    },
    {
      "name": "nav-ink-muted",
      "cssVar": "--co-nav-ink-muted",
      "value": {
        "classic": "#FFFFFF",
        "sidebar": "#5B6B69",
        "rail": "#C0C3CB",
        "command": "#6B7280",
        "dark": "#93A3A0"
      },
      "usage": "Inactive rail icons on `nav-bg` (source: white at 72% on the slate rail)."
    },
    {
      "name": "focus-ring",
      "cssVar": "--co-focus-ring",
      "value": {
        "classic": "#2E5880",
        "sidebar": "#0F766E",
        "rail": "#3B4FD8",
        "command": "#166534",
        "dark": "#5EEAD4"
      },
      "usage": "2px solid keyboard focus outline with 2px offset, on every control. An added rule: the screens set no focus style of their own."
    },
    {
      "name": "toast-bg",
      "cssVar": "--co-toast-bg",
      "value": {
        "classic": "#1F2937",
        "sidebar": "#0B1F1E",
        "rail": "#111827",
        "command": "#111827",
        "dark": "#E8EFEE"
      },
      "usage": "Toast background (source: `ink`). Text `toast-ink` on it."
    },
    {
      "name": "toast-ink",
      "cssVar": "--co-toast-ink",
      "value": {
        "classic": "#FFFFFF",
        "sidebar": "#FFFFFF",
        "rail": "#FFFFFF",
        "command": "#FFFFFF",
        "dark": "#0E1514"
      },
      "usage": "Toast text on `toast-bg`."
    },
    {
      "name": "overlay",
      "cssVar": "--co-overlay",
      "value": {
        "classic": "rgba(17, 24, 39, 0.45)",
        "sidebar": "rgba(17, 24, 39, 0.45)",
        "rail": "rgba(17, 24, 39, 0.45)",
        "command": "rgba(17, 24, 39, 0.45)",
        "dark": "rgba(0, 0, 0, 0.6)"
      },
      "usage": "Scrim behind modals, drawers and the command palette."
    },
    {
      "name": "success",
      "cssVar": "--co-success",
      "value": {
        "classic": "#1E9E5A",
        "sidebar": "#1E9E5A",
        "rail": "#1E9E5A",
        "command": "#1E9E5A",
        "dark": "#34D399"
      },
      "usage": "Success circle, checked switch, completed step and appointment stripe. Icons on it use `on-status`."
    },
    {
      "name": "success-strong",
      "cssVar": "--co-success-strong",
      "value": {
        "classic": "#13703F",
        "sidebar": "#13703F",
        "rail": "#13703F",
        "command": "#13703F",
        "dark": "#6EE7B7"
      },
      "usage": "Success text on `success-soft` (Approved, Paid, Eligible tags)."
    },
    {
      "name": "success-soft",
      "cssVar": "--co-success-soft",
      "value": {
        "classic": "#D9F8E6",
        "sidebar": "#D9F8E6",
        "rail": "#D9F8E6",
        "command": "#D9F8E6",
        "dark": "#0F3324"
      },
      "usage": "Success tag and Completed appointment background."
    },
    {
      "name": "danger",
      "cssVar": "--co-danger",
      "value": {
        "classic": "#D9342B",
        "sidebar": "#D9342B",
        "rail": "#D9342B",
        "command": "#D9342B",
        "dark": "#F87171"
      },
      "usage": "Required asterisk, field error text and border, delete button text, notification count badge, No Show stripe."
    },
    {
      "name": "danger-strong",
      "cssVar": "--co-danger-strong",
      "value": {
        "classic": "#B42318",
        "sidebar": "#B42318",
        "rail": "#B42318",
        "command": "#B42318",
        "dark": "#FCA5A5"
      },
      "usage": "Danger tag text on `danger-soft` (Denied, Rejected, Allergy)."
    },
    {
      "name": "danger-soft",
      "cssVar": "--co-danger-soft",
      "value": {
        "classic": "#FDE4E2",
        "sidebar": "#FDE4E2",
        "rail": "#FDE4E2",
        "command": "#FDE4E2",
        "dark": "#3B1717"
      },
      "usage": "Danger tag, error banner and allergy strip background."
    },
    {
      "name": "danger-line",
      "cssVar": "--co-danger-line",
      "value": {
        "classic": "#F1B9B5",
        "sidebar": "#F1B9B5",
        "rail": "#F1B9B5",
        "command": "#F1B9B5",
        "dark": "#7F2A2A"
      },
      "usage": "Border of the danger button and error banner."
    },
    {
      "name": "danger-ink",
      "cssVar": "--co-danger-ink",
      "value": {
        "classic": "#7A1D16",
        "sidebar": "#7A1D16",
        "rail": "#7A1D16",
        "command": "#7A1D16",
        "dark": "#FECACA"
      },
      "usage": "Body text inside the error banner and restricted-chart box on `danger-soft`."
    },
    {
      "name": "warning",
      "cssVar": "--co-warning",
      "value": {
        "classic": "#C8961E",
        "sidebar": "#C8961E",
        "rail": "#C8961E",
        "command": "#C8961E",
        "dark": "#FBBF24"
      },
      "usage": "Arrived and Checked In appointment stripe, low-value bar. Never text."
    },
    {
      "name": "warning-strong",
      "cssVar": "--co-warning-strong",
      "value": {
        "classic": "#7A5A12",
        "sidebar": "#7A5A12",
        "rail": "#7A5A12",
        "command": "#7A5A12",
        "dark": "#FDE68A"
      },
      "usage": "Warning tag text on `warning-soft` (Pending, Pended, Expiring)."
    },
    {
      "name": "warning-soft",
      "cssVar": "--co-warning-soft",
      "value": {
        "classic": "#FCF3CC",
        "sidebar": "#FCF3CC",
        "rail": "#FCF3CC",
        "command": "#FCF3CC",
        "dark": "#3A2E0A"
      },
      "usage": "Warning tag and Arrived appointment background."
    },
    {
      "name": "warning-box",
      "cssVar": "--co-warning-box",
      "value": {
        "classic": "#FFF4E5",
        "sidebar": "#FFF4E5",
        "rail": "#FFF4E5",
        "command": "#FFF4E5",
        "dark": "#2E2410"
      },
      "usage": "Warning banner background (holds `ink`)."
    },
    {
      "name": "warning-line",
      "cssVar": "--co-warning-line",
      "value": {
        "classic": "#F5C98A",
        "sidebar": "#F5C98A",
        "rail": "#F5C98A",
        "command": "#F5C98A",
        "dark": "#8A6A1F"
      },
      "usage": "Warning banner border."
    },
    {
      "name": "ai",
      "cssVar": "--co-ai",
      "value": {
        "classic": "#6B2A8C",
        "sidebar": "#6B2A8C",
        "rail": "#6B2A8C",
        "command": "#6B2A8C",
        "dark": "#C084FC"
      },
      "usage": "AI actions and AI-made content: AI button fill, In Room stripe, AI spinner. Text `ai-ink` on it; as text on `ai-soft`."
    },
    {
      "name": "ai-ink",
      "cssVar": "--co-ai-ink",
      "value": {
        "classic": "#FFFFFF",
        "sidebar": "#FFFFFF",
        "rail": "#FFFFFF",
        "command": "#FFFFFF",
        "dark": "#2A0E3A"
      },
      "usage": "Text on the `ai` fill."
    },
    {
      "name": "ai-soft",
      "cssVar": "--co-ai-soft",
      "value": {
        "classic": "#F5F2FA",
        "sidebar": "#F5F2FA",
        "rail": "#F5F2FA",
        "command": "#F5F2FA",
        "dark": "#2E263A"
      },
      "usage": "AI suggestion box and AI tag background."
    },
    {
      "name": "ai-line",
      "cssVar": "--co-ai-line",
      "value": {
        "classic": "#ECC8E3",
        "sidebar": "#ECC8E3",
        "rail": "#ECC8E3",
        "command": "#ECC8E3",
        "dark": "#5B2D73"
      },
      "usage": "AI suggestion box border."
    },
    {
      "name": "on-status",
      "cssVar": "--co-on-status",
      "value": {
        "classic": "#FFFFFF",
        "sidebar": "#FFFFFF",
        "rail": "#FFFFFF",
        "command": "#FFFFFF",
        "dark": "#0E1514"
      },
      "usage": "Icon or count text on `success` and `danger` fills."
    },
    {
      "name": "on-accent",
      "cssVar": "--co-on-accent",
      "value": {
        "classic": "#FFFFFF",
        "sidebar": "#FFFFFF",
        "rail": "#FFFFFF",
        "command": "#FFFFFF",
        "dark": "#0E1514"
      },
      "usage": "Initials on the account avatar (`accent` fill).21:1; rail: `on-accent` on `accent` is 3.29:1; command: `on-accent` on `accent` is 2.94:1. Passes 4.5:1 in every theme since the 10/09/2026 accent fix (was 2.21:1 Classic, 3.29:1 Focus Rail, 2.94:1 Command Bar)."
    },
    {
      "name": "appt-blue",
      "cssVar": "--co-appt-blue",
      "value": {
        "classic": "#5281DD",
        "sidebar": "#569792",
        "rail": "#7482E4",
        "command": "#659978",
        "dark": "#7AA2F7"
      },
      "usage": "Default appointment type colour (New Patient). Follows the style: `primary-line`. Used as the 4px left stripe and legend dot only, always next to the type name; the chip text stays `ink` on `surface-alt`. As a mark it is below 3:1 on `surface-alt` for Blue, Teal, Orange and Yellow in the light styles (source colours kept), so colour never carries the type alone. Contrast fix applied 10/09/2026 (lightness only, hue and saturation kept, WCAG 2 formula): Clinical Sidebar was #6FADA8 (surface-alt 2.28:1, under 3:1 for appointment stripe (non-text, 3:1)); Focus Rail was #8995E8 (surface-alt 2.43:1, under 3:1 for appointment stripe (non-text, 3:1)); Command Bar was #73A385 (surface-alt 2.64:1, under 3:1 for appointment stripe (non-text, 3:1))."
    },
    {
      "name": "appt-green",
      "cssVar": "--co-appt-green",
      "value": {
        "classic": "#1E9E5A",
        "sidebar": "#1E9E5A",
        "rail": "#1E9D59",
        "command": "#1E9E5A",
        "dark": "#1E9E5A"
      },
      "usage": "Follow-Up and other routine types. Used as the 4px left stripe and legend dot only, always next to the type name; the chip text stays `ink` on `surface-alt`. After the 10/09/2026 fixes every appointment colour reaches 3:1 on `surface` and `surface-alt` in all five themes (build/contrast_check.py); colour still never carries the type alone. Contrast fix applied 10/09/2026 (lightness only, hue and saturation kept, WCAG 2 formula): Focus Rail was #1E9E5A (surface 3.45:1, surface-alt 3.00:1, under 3:1 for appointment stripe and legend dot (3:1 non-text))."
    },
    {
      "name": "appt-teal",
      "cssVar": "--co-appt-teal",
      "value": {
        "classic": "#139B9B",
        "sidebar": "#139B9B",
        "rail": "#139999",
        "command": "#139E9E",
        "dark": "#14A3A3"
      },
      "usage": "Procedures and screenings. Used as the 4px left stripe and legend dot only, always next to the type name; the chip text stays `ink` on `surface-alt`. As a mark it is below 3:1 on `surface-alt` for Blue, Teal, Orange and Yellow in the light styles (source colours kept), so colour never carries the type alone. Contrast fix applied 10/09/2026 (lightness only, hue and saturation kept, WCAG 2 formula): Classic was #14A3A3 (surface-alt 2.75:1, under 3:1 for appointment stripe (non-text, 3:1)); Clinical Sidebar was #14A3A3 (surface-alt 2.75:1, under 3:1 for appointment stripe (non-text, 3:1)); Focus Rail was #14A3A3 (surface-alt 2.69:1, under 3:1 for appointment stripe (non-text, 3:1)); Command Bar was #14A3A3 (surface-alt 2.84:1, under 3:1 for appointment stripe (non-text, 3:1))."
    },
    {
      "name": "appt-purple",
      "cssVar": "--co-appt-purple",
      "value": {
        "classic": "#6B2A8C",
        "sidebar": "#6B2A8C",
        "rail": "#6B2A8C",
        "command": "#6B2A8C",
        "dark": "#B57BD6"
      },
      "usage": "Behavioral health types; also the AI purple. Used as the 4px left stripe and legend dot only, always next to the type name; the chip text stays `ink` on `surface-alt`. As a mark it is below 3:1 on `surface-alt` for Blue, Teal, Orange and Yellow in the light styles (source colours kept), so colour never carries the type alone."
    },
    {
      "name": "appt-red",
      "cssVar": "--co-appt-red",
      "value": {
        "classic": "#D9342B",
        "sidebar": "#D9342B",
        "rail": "#D9342B",
        "command": "#D9342B",
        "dark": "#D9342B"
      },
      "usage": "Urgent and same-day types. Used as the 4px left stripe and legend dot only, always next to the type name; the chip text stays `ink` on `surface-alt`. As a mark it is below 3:1 on `surface-alt` for Blue, Teal, Orange and Yellow in the light styles (source colours kept), so colour never carries the type alone."
    },
    {
      "name": "appt-orange",
      "cssVar": "--co-appt-orange",
      "value": {
        "classic": "#D17419",
        "sidebar": "#D17419",
        "rail": "#CE7219",
        "command": "#D47619",
        "dark": "#E47F1C"
      },
      "usage": "Physical therapy and rehab types. Used as the 4px left stripe and legend dot only, always next to the type name; the chip text stays `ink` on `surface-alt`. As a mark it is below 3:1 on `surface-alt` for Blue, Teal, Orange and Yellow in the light styles (source colours kept), so colour never carries the type alone. Contrast fix applied 10/09/2026 (lightness only, hue and saturation kept, WCAG 2 formula): Classic was #E47F1C (surface-alt 2.54:1, under 3:1 for appointment stripe (non-text, 3:1)); Clinical Sidebar was #E47F1C (surface-alt 2.55:1, under 3:1 for appointment stripe (non-text, 3:1)); Focus Rail was #E47F1C (surface-alt 2.48:1, under 3:1 for appointment stripe (non-text, 3:1)); Command Bar was #E47F1C (surface-alt 2.63:1, under 3:1 for appointment stripe (non-text, 3:1))."
    },
    {
      "name": "appt-yellow",
      "cssVar": "--co-appt-yellow",
      "value": {
        "classic": "#AC8610",
        "sidebar": "#AC8610",
        "rail": "#AA8510",
        "command": "#B08911",
        "dark": "#E7B416"
      },
      "usage": "Annual wellness and preventive types. Used as the 4px left stripe and legend dot only, always next to the type name; the chip text stays `ink` on `surface-alt`. As a mark it is below 3:1 on `surface-alt` for Blue, Teal, Orange and Yellow in the light styles (source colours kept), so colour never carries the type alone. Contrast fix applied 10/09/2026 (lightness only, hue and saturation kept, WCAG 2 formula): Classic was #E7B416 (surface-alt 1.71:1, under 3:1 for appointment stripe (non-text, 3:1)); Clinical Sidebar was #E7B416 (surface-alt 1.71:1, under 3:1 for appointment stripe (non-text, 3:1)); Focus Rail was #E7B416 (surface-alt 1.67:1, under 3:1 for appointment stripe (non-text, 3:1)); Command Bar was #E7B416 (surface-alt 1.76:1, under 3:1 for appointment stripe (non-text, 3:1))."
    },
    {
      "name": "appt-pink",
      "cssVar": "--co-appt-pink",
      "value": {
        "classic": "#D6489B",
        "sidebar": "#D6489B",
        "rail": "#D6489B",
        "command": "#D6489B",
        "dark": "#D6489B"
      },
      "usage": "OB/GYN and prenatal types. Used as the 4px left stripe and legend dot only, always next to the type name; the chip text stays `ink` on `surface-alt`. As a mark it is below 3:1 on `surface-alt` for Blue, Teal, Orange and Yellow in the light styles (source colours kept), so colour never carries the type alone."
    },
    {
      "name": "appt-gray",
      "cssVar": "--co-appt-gray",
      "value": {
        "classic": "#6B7280",
        "sidebar": "#5B6B69",
        "rail": "#64748B",
        "command": "#6B7280",
        "dark": "#93A3A0"
      },
      "usage": "Admin and blocked-time types. Used as the 4px left stripe and legend dot only, always next to the type name; the chip text stays `ink` on `surface-alt`. As a mark it is below 3:1 on `surface-alt` for Blue, Teal, Orange and Yellow in the light styles (source colours kept), so colour never carries the type alone."
    }
  ],
  "spacing": [
    {
      "name": "space-1",
      "cssVar": "--co-space-1",
      "value": "4px",
      "usage": "Icon-to-text gap in tags, menu padding."
    },
    {
      "name": "space-1-5",
      "cssVar": "--co-space-1-5",
      "value": "6px",
      "usage": "Gap between buttons in a toolbar; label to field."
    },
    {
      "name": "space-2",
      "cssVar": "--co-space-2",
      "value": "8px",
      "usage": "Button group gap, compact card padding (10px)."
    },
    {
      "name": "space-2-5",
      "cssVar": "--co-space-2-5",
      "value": "10px",
      "usage": "Input inner padding, nav item padding."
    },
    {
      "name": "space-3",
      "cssVar": "--co-space-3",
      "value": "12px",
      "usage": "Default gap of .row, .grid2, .grid3, .wrap padding."
    },
    {
      "name": "space-3-5",
      "cssVar": "--co-space-3-5",
      "value": "14px",
      "usage": "Modal header and footer vertical padding, stat card padding."
    },
    {
      "name": "space-4",
      "cssVar": "--co-space-4",
      "value": "16px",
      "usage": "Card padding, mobile body side padding, phone gutter."
    },
    {
      "name": "space-5",
      "cssVar": "--co-space-5",
      "value": "20px",
      "usage": "Modal body and header side padding, kiosk body."
    },
    {
      "name": "space-6",
      "cssVar": "--co-space-6",
      "value": "24px",
      "usage": "Settings row column gap, toast bottom offset."
    }
  ],
  "radius": [
    {
      "name": "radius-xs",
      "cssVar": "--co-radius-xs",
      "value": "4px",
      "usage": "Inputs, tags, slots, menu items, calendar chips."
    },
    {
      "name": "radius-sm",
      "cssVar": "--co-radius-sm",
      "value": "6px",
      "usage": "Buttons, menus, banners, table frame."
    },
    {
      "name": "radius-md",
      "cssVar": "--co-radius-md",
      "value": "8px",
      "usage": "Cards, stat cards, nav items, toasts, search box."
    },
    {
      "name": "radius-lg",
      "cssVar": "--co-radius-lg",
      "value": "10px",
      "usage": "Shell menus, rail items, patient tabs, drop zones."
    },
    {
      "name": "radius-xl",
      "cssVar": "--co-radius-xl",
      "value": "12px",
      "usage": "Modals, chat bubbles, PIN keys."
    },
    {
      "name": "radius-2xl",
      "cssVar": "--co-radius-2xl",
      "value": "14px",
      "usage": "Command palette."
    },
    {
      "name": "radius-sheet",
      "cssVar": "--co-radius-sheet",
      "value": "16px",
      "usage": "Top corners of the mobile bottom sheet."
    },
    {
      "name": "radius-pill",
      "cssVar": "--co-radius-pill",
      "value": "999px",
      "usage": "Chips, pills, badges, switches, avatars, progress bars."
    }
  ],
  "shadow": [
    {
      "name": "shadow-card",
      "cssVar": "--co-shadow-card",
      "value": {
        "classic": "0 1px 3px rgba(16, 24, 40, 0.08)",
        "sidebar": "0 1px 3px rgba(16, 24, 40, 0.08)",
        "rail": "0 1px 3px rgba(16, 24, 40, 0.08)",
        "command": "none",
        "dark": "none"
      },
      "usage": "Cards. Command Bar uses a 1px `border` instead of a shadow; Dark relies on borders."
    },
    {
      "name": "shadow-pop",
      "cssVar": "--co-shadow-pop",
      "value": "0 12px 32px rgba(16, 24, 40, 0.18)",
      "usage": "Menus, modals, drawers."
    },
    {
      "name": "shadow-toast",
      "cssVar": "--co-shadow-toast",
      "value": "0 12px 32px rgba(16, 24, 40, 0.25)",
      "usage": "Toast."
    },
    {
      "name": "shadow-palette",
      "cssVar": "--co-shadow-palette",
      "value": "0 24px 60px rgba(0, 0, 0, 0.3)",
      "usage": "Command palette."
    },
    {
      "name": "shadow-seg",
      "cssVar": "--co-shadow-seg",
      "value": "0 1px 2px rgba(16, 24, 40, 0.12)",
      "usage": "Selected segment of a segmented control."
    }
  ],
  "zIndex": [
    {
      "name": "z-menu",
      "cssVar": "--co-z-menu",
      "value": "30",
      "usage": "Row menus and dropdowns inside a page."
    },
    {
      "name": "z-nav",
      "cssVar": "--co-z-nav",
      "value": "40",
      "usage": "Sidebar and rail; also the page overlay (.ov) in the source."
    },
    {
      "name": "z-toast",
      "cssVar": "--co-z-toast",
      "value": "60",
      "usage": "Toasts and shell menus."
    },
    {
      "name": "z-tooltip",
      "cssVar": "--co-z-tooltip",
      "value": "70",
      "usage": "Rail tooltips."
    },
    {
      "name": "z-palette",
      "cssVar": "--co-z-palette",
      "value": "80",
      "usage": "Command palette and mobile nav overlay."
    }
  ],
  "density": [
    {
      "name": "control-h",
      "cssVar": "--co-control-h",
      "value": "36px",
      "usage": "Button and input height, Comfortable."
    },
    {
      "name": "control-h-compact",
      "cssVar": "--co-control-h-compact",
      "value": "30px",
      "usage": "Button and input height in Compact density and the sm size."
    },
    {
      "name": "control-h-touch",
      "cssVar": "--co-control-h-touch",
      "value": "44px",
      "usage": "Minimum tap target on phone screens."
    },
    {
      "name": "control-h-kiosk",
      "cssVar": "--co-control-h-kiosk",
      "value": "48px",
      "usage": "Kiosk buttons and inputs; the lg size."
    },
    {
      "name": "cell-py",
      "cssVar": "--co-cell-py",
      "value": "9px",
      "usage": "Table cell vertical padding, Comfortable (Compact: 4px)."
    },
    {
      "name": "side-w",
      "cssVar": "--co-side-w",
      "value": "240px",
      "usage": "Clinical Sidebar width; 64px collapsed and for the rail."
    },
    {
      "name": "topbar-h",
      "cssVar": "--co-topbar-h",
      "value": "52px",
      "usage": "Top bar height."
    },
    {
      "name": "content-max",
      "cssVar": "--co-content-max",
      "value": "1440px",
      "usage": "Max width of the page wrap."
    }
  ],
  "typography": {
    "families": {
      "sans": {
        "cssVar": "--co-font-sans",
        "value": "Roboto, \"Helvetica Neue\", Arial, sans-serif"
      },
      "mono": {
        "cssVar": "--co-font-mono",
        "value": "\"Roboto Mono\", Menlo, monospace"
      },
      "script": {
        "cssVar": "--co-font-script",
        "value": "\"Brush Script MT\", cursive"
      }
    },
    "groups": [
      {
        "name": "Headings",
        "family": "sans",
        "styles": [
          {
            "name": "kiosk-title",
            "fontSize": "24px",
            "lineHeight": "30px",
            "fontWeight": 500,
            "sample": "Welcome, please check in",
            "usage": "Kiosk page heading (.kh)."
          },
          {
            "name": "kpi-value",
            "fontSize": "24px",
            "lineHeight": "30px",
            "fontWeight": 500,
            "sample": "1,284",
            "usage": "Stat card number."
          },
          {
            "name": "h1",
            "fontSize": "20px",
            "lineHeight": "26px",
            "fontWeight": 500,
            "sample": "Patient chart",
            "usage": "Page title and patient name in the banner."
          },
          {
            "name": "brand",
            "fontSize": "17px",
            "lineHeight": "22px",
            "fontWeight": 700,
            "letterSpacing": "-0.2px",
            "sample": "CareOS",
            "usage": "Logo word in the top bar; mobile header title uses 17px 500."
          },
          {
            "name": "h2",
            "fontSize": "16px",
            "lineHeight": "22px",
            "fontWeight": 500,
            "sample": "Claim lines",
            "usage": "Card and modal titles."
          },
          {
            "name": "h3",
            "fontSize": "14px",
            "lineHeight": "20px",
            "fontWeight": 500,
            "sample": "Diagnosis pointers",
            "usage": "Sub-section titles inside cards."
          }
        ]
      },
      {
        "name": "Text",
        "family": "sans",
        "styles": [
          {
            "name": "body",
            "fontSize": "14px",
            "lineHeight": "20px",
            "fontWeight": 400,
            "sample": "Henna West, F, 38 y",
            "usage": "Default text, inputs, menu items, buttons (at 500)."
          },
          {
            "name": "label",
            "fontSize": "13px",
            "lineHeight": "18px",
            "fontWeight": 500,
            "sample": "Date of Birth",
            "usage": "Field labels; table text (13px 400) and sub-titles."
          },
          {
            "name": "table",
            "fontSize": "13px",
            "lineHeight": "19px",
            "fontWeight": 400,
            "sample": "99214 Office visit, est.",
            "usage": "Table cells, notes, key-value lists."
          },
          {
            "name": "helper",
            "fontSize": "12px",
            "lineHeight": "16px",
            "fontWeight": 400,
            "sample": "Format (312) 555-0142",
            "usage": "Helper and error text, tags (at 500), legends."
          },
          {
            "name": "overline",
            "fontSize": "11px",
            "lineHeight": "14px",
            "fontWeight": 700,
            "letterSpacing": "0.06em",
            "sample": "FRONT OFFICE",
            "usage": "Sidebar group labels and stat labels (0.3px tracking there). Uppercase."
          },
          {
            "name": "micro",
            "fontSize": "11px",
            "lineHeight": "14px",
            "fontWeight": 500,
            "sample": "Behavioral Health",
            "usage": "Dense tags, bottom tab labels, kbd hints."
          }
        ]
      },
      {
        "name": "Special",
        "family": "sans",
        "styles": [
          {
            "name": "signature",
            "family": "script",
            "fontSize": "28px",
            "lineHeight": "34px",
            "fontWeight": 400,
            "fontStyle": "italic",
            "sample": "Henna West",
            "usage": "Typed signature on kiosk and consent (26px on mobile)."
          },
          {
            "name": "pin-key",
            "fontSize": "20px",
            "lineHeight": "24px",
            "fontWeight": 500,
            "sample": "1 2 3",
            "usage": "PIN keypad keys."
          },
          {
            "name": "code",
            "family": "mono",
            "fontSize": "12px",
            "lineHeight": "17px",
            "fontWeight": 500,
            "sample": "GET /fhir/Patient/100231",
            "usage": "Developer drawer snippets, X12 segments."
          }
        ]
      }
    ]
  }
} as const;

export type ColorToken = (typeof tokens.color)[number]['name'];

/** `var(--co-<name>)` for any token name. */
export function tokenVar(name: string): string {
  return `var(--co-${name})`;
}

/** The value of a colour token in a theme (falls back to the default theme). */
export function colorValue(name: ColorToken, theme: ThemeId = 'classic'): string | undefined {
  const t = tokens.color.find((c) => c.name === name);
  if (!t) return undefined;
  const v = t.value as string | Record<string, string>;
  return typeof v === 'string' ? v : (v[theme] ?? v['classic']);
}
