import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  guides: [
    'intro',
    {
      type: 'category',
      label: 'Getting started',
      collapsed: false,
      items: [
        'getting-started/react',
        'getting-started/angular',
        'getting-started/vue',
        'getting-started/html',
        'getting-started/theming',
        'getting-started/nextjs',
      ],
    },
    'screen-recipes',
    'role-based-ui',
  ],
  foundations: [
    'foundations/overview',
    'foundations/color',
    'foundations/typography',
    'foundations/layout',
    'foundations/iconography',
    'foundations/content-voice',
    'foundations/accessibility',
  ],
  components: [{ type: 'autogenerated', dirName: 'components' }],
};

export default sidebars;
